[project]
name = "tracin-pytorch"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click~=8.1.7",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "tqdm~=4.66.2",
]
